### ISSUE TITLE
GET /api/cart/user/ (without providing an ID) causes an Application Error

### ISSUE THREAD

**Issue by donny-nyc** [Honey-Bunches-Grace-Shopper/GraceShopper#64]
For bugs, please include the following:

* What is the expected behavior?
Graceful error handling, or an OK response with results
* What is the actual behavior?
![2020-12-28-121804_1916x1035_scrot](https://user-images.githubusercontent.com/2840641/103238073-9488c980-4917-11eb-89b1-f2c9a6a7af74.png)

* What steps reproduce the behavior?
`GET /api/cart/user/`

For features, please specify at least minimal requirements, e.g.:

* "As an API user, I should receive a 4xx error response if the user ID is required, else a 200 response with the expected results (if any)"

---

_Issue description here…_
@ellengranoff 
As you can see in the attached screenshot, making a `GET` request to the `/api/cart/user/` endpoint _without_ providing a user ID causes an application error.

**Comment by ellengranoff** [comment]
@donny-nyc - I added a route for the /api/cart/user/ endpoint which handles instances where a userId is not provided. This now generates a 404 error as a fix. Thanks for your input; the project is certainly better for it.
