### ISSUE TITLE
As a user, I am able to view the contents of another user's Nest

### ISSUE THREAD

**Issue by donny-nyc** [Honey-Bunches-Grace-Shopper/GraceShopper#65]
For bugs, please include the following:

* What is the expected behavior?
Requests to `GET /api/cart/users/[:user_id:]` should return a `401 Not Authorized` response unless I am currently signed in as that user. Requests to the same endpoint must only return a `200 OK` response if I am authorized.
* What is the actual behavior?
Requests to the same endpoint return a `200 OK` response with a JSON payload listing the contents of that user's ~~cart~~ nest
* What steps reproduce the behavior?
1. Create two user accounts
2. As one of the users, add ducks to your nest
3. log out as that user, and sign in as the other
4. `GET /api/cart/users/[:user_id:]` with the first user's id (the user with a non-empty nest)
5. Observe that the response returns a `200 OK` and a JSON payload representing that user's nest

For features, please specify at least minimal requirements, e.g.:
As a non-admin user, I must not be able to view the contents of another user's nest.
Requests to `GET /api/cart/users/[:user_id:]/ should return a `401 Not Authorized` unless I am requesting my own cart, in which case the endpoint should return a `200 OK` response

---

_Issue description here…_
@ellengranoff 
While signed in as user 43, I am able to view the contents of user 42's nest
![2020-12-28-122407_1916x1035_scrot](https://user-images.githubusercontent.com/2840641/103238632-4b397980-4919-11eb-8c81-745ffa3500ef.png)
![2020-12-28-123111_1916x1035_scrot](https://user-images.githubusercontent.com/2840641/103238659-5a202c00-4919-11eb-8cfc-3b5525619275.png)

**Comment by ellengranoff** [comment]
@donny-nyc - thank you for the feedback on this! You identified a major security issue with that route. 

I just implemented some new route security measures for GET Requests to  /api/cart/users/[:user_id:] - this route is now restricted to logged in users with an id that matches the userId on the req.params object. 

Your comment inspired me to protect a few of our other routes as well, to ensure that users cannot modify or delete anything in one another's carts. The new security features block non-logged in users as well as those accessing the routes with API development tools like Postman. The app is updated and redeployed on Heroku now.
